# Generated by Django 3.2.19 on 2023-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0257_alter_membership_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start',), 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('domain',), 'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='consortium',
            field=models.BooleanField(default=False, help_text='Determines whether this is a group of hosts working together under a consortium.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='variant',
            field=models.CharField(choices=[('partner', 'Partner'), ('lmic_host', 'LMIC Host'), ('sponsor', 'Sponsor'), ('hic_host', 'HIC Host'), ('funder', 'Funder'), ('potential_support', 'Potential Support')], max_length=40),
        ),
    ]
