# Generated by Django 3.2.19 on 2023-06-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0258_auto_20230616_1125'),
        ('workshops', '0258_auto_20230616_1213'),
    ]

    operations = [
    ]
