# Generated by Django 3.2.19 on 2023-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrequests', '0030_auto_20211231_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopinquiryrequest',
            name='administrative_fee',
            field=models.CharField(choices=[('nonprofit', 'I am with a government site, university, or other nonprofit. I understand the workshop fee as listed on The Carpentries website and agree to follow through on The Carpentries invoicing process.'), ('forprofit', 'I am with a corporate or for-profit site. I understand the costs for for-profit hosts are four times the price for not-for-profit hosts.'), ('member', 'I am with a Member host so the workshop fee does not apply (instructor travel costs will still apply for in-person workshops).'), ('waiver', 'I am requesting financial support for the workshop fee (instructor travel costs will still apply for in-person workshops)')], default=None, help_text="<a href='https://carpentries.org/workshops/#workshop-cost' target='_blank' rel='noreferrer nofollow'>The Carpentries website workshop fee listing.</a>", max_length=20, verbose_name='Which of the following applies to your payment for the administrative fee?'),
        ),
    ]
